Traceback (most recent call last):
  File "c:\users\ryanshen\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\ryanshen\anaconda3\lib\site-packages\nbclient\client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ryanshen\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ryanshen\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ryanshen\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\ryanshen\anaconda3\lib\site-packages\nbclient\client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "c:\users\ryanshen\anaconda3\lib\site-packages\nbclient\client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\ryanshen\anaconda3\lib\site-packages\nbclient\client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
obj[['']]
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
[1;32m<ipython-input-53-06f411871508>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mobj[0m[1;33m[[0m[1;33m[[0m[1;34m''[0m[1;33m][0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m
[1;32m~\anaconda3\lib\site-packages\pandas\core\series.py[0m in [0;36m__getitem__[1;34m(self, key)[0m
[0;32m    908[0m             [0mkey[0m [1;33m=[0m [0mcheck_bool_indexer[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mindex[0m[1;33m,[0m [0mkey[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    909[0m [1;33m[0m[0m
[1;32m--> 910[1;33m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_get_with[0m[1;33m([0m[0mkey[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    911[0m [1;33m[0m[0m
[0;32m    912[0m     [1;32mdef[0m [0m_get_with[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mkey[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\core\series.py[0m in [0;36m_get_with[1;34m(self, key)[0m
[0;32m    956[0m                 [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_get_values[0m[1;33m([0m[0mkey[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m    957[0m [1;33m[0m[0m
[1;32m--> 958[1;33m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0mloc[0m[1;33m[[0m[0mkey[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    959[0m [1;33m[0m[0m
[0;32m    960[0m         [1;32mreturn[0m [0mself[0m[1;33m.[0m[0mreindex[0m[1;33m([0m[0mkey[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\core\indexing.py[0m in [0;36m__getitem__[1;34m(self, key)[0m
[0;32m   1766[0m [1;33m[0m[0m
[0;32m   1767[0m             [0mmaybe_callable[0m [1;33m=[0m [0mcom[0m[1;33m.[0m[0mapply_if_callable[0m[1;33m([0m[0mkey[0m[1;33m,[0m [0mself[0m[1;33m.[0m[0mobj[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1768[1;33m             [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_getitem_axis[0m[1;33m([0m[0mmaybe_callable[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1769[0m [1;33m[0m[0m
[0;32m   1770[0m     [1;32mdef[0m [0m_is_scalar_access[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mkey[0m[1;33m:[0m [0mTuple[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\core\indexing.py[0m in [0;36m_getitem_axis[1;34m(self, key, axis)[0m
[0;32m   1952[0m                     [1;32mraise[0m [0mValueError[0m[1;33m([0m[1;34m"Cannot index with multidimensional key"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1953[0m [1;33m[0m[0m
[1;32m-> 1954[1;33m                 [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_getitem_iterable[0m[1;33m([0m[0mkey[0m[1;33m,[0m [0maxis[0m[1;33m=[0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1955[0m [1;33m[0m[0m
[0;32m   1956[0m             [1;31m# nested tuple slicing[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\core\indexing.py[0m in [0;36m_getitem_iterable[1;34m(self, key, axis)[0m
[0;32m   1593[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1594[0m             [1;31m# A collection of keys[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1595[1;33m             [0mkeyarr[0m[1;33m,[0m [0mindexer[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_get_listlike_indexer[0m[1;33m([0m[0mkey[0m[1;33m,[0m [0maxis[0m[1;33m,[0m [0mraise_missing[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1596[0m             return self.obj._reindex_with_indexers(
[0;32m   1597[0m                 [1;33m{[0m[0maxis[0m[1;33m:[0m [1;33m[[0m[0mkeyarr[0m[1;33m,[0m [0mindexer[0m[1;33m][0m[1;33m}[0m[1;33m,[0m [0mcopy[0m[1;33m=[0m[1;32mTrue[0m[1;33m,[0m [0mallow_dups[0m[1;33m=[0m[1;32mTrue[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\core\indexing.py[0m in [0;36m_get_listlike_indexer[1;34m(self, key, axis, raise_missing)[0m
[0;32m   1550[0m             [0mkeyarr[0m[1;33m,[0m [0mindexer[0m[1;33m,[0m [0mnew_indexer[0m [1;33m=[0m [0max[0m[1;33m.[0m[0m_reindex_non_unique[0m[1;33m([0m[0mkeyarr[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1551[0m [1;33m[0m[0m
[1;32m-> 1552[1;33m         self._validate_read_indexer(
[0m[0;32m   1553[0m             [0mkeyarr[0m[1;33m,[0m [0mindexer[0m[1;33m,[0m [0mo[0m[1;33m.[0m[0m_get_axis_number[0m[1;33m([0m[0maxis[0m[1;33m)[0m[1;33m,[0m [0mraise_missing[0m[1;33m=[0m[0mraise_missing[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1554[0m         )

[1;32m~\anaconda3\lib\site-packages\pandas\core\indexing.py[0m in [0;36m_validate_read_indexer[1;34m(self, key, indexer, axis, raise_missing)[0m
[0;32m   1638[0m             [1;32mif[0m [0mmissing[0m [1;33m==[0m [0mlen[0m[1;33m([0m[0mindexer[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1639[0m                 [0maxis_name[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0mobj[0m[1;33m.[0m[0m_get_axis_name[0m[1;33m([0m[0maxis[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1640[1;33m                 [1;32mraise[0m [0mKeyError[0m[1;33m([0m[1;34mf"None of [{key}] are in the [{axis_name}]"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1641[0m [1;33m[0m[0m
[0;32m   1642[0m             [1;31m# We (temporarily) allow for some missing keys with .loc, except in[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;31mKeyError[0m: "None of [Index([''], dtype='object')] are in the [index]"
KeyError: "None of [Index([''], dtype='object')] are in the [index]"

